[package]
name = "smb2"
version = "0.1.0"
authors = ["Alexander Theißen <alex@theissen.io>"]
edition = "2018"

[dependencies]
nom = "4.1.0"
bitflags = "1.0.4"
byteorder = "1.2.6"

[dev-dependencies]
slice-deque = "0.1.14"
ether = "0.1.4"
